export type Role = 'ADMIN' | 'MANAGER' | 'SALES' | 'PURCHASE' | 'LOGISTICS' | 'VIEWER';
export type Direction = 'IMPORT' | 'EXPORT';
export interface Profile { id: string; full_name?: string; role: Role; department?: string; created_at?: string; updated_at?: string }
export interface Customer { id: string; customer_name: string; customer_code?: string; city?: string; state?: string; country?: string; sales_person?: string; created_at?: string; updated_at?: string }
export interface Supplier { id: string; supplier_name: string; supplier_code?: string; country?: string; contact_person?: string; email?: string; phone?: string; created_at?: string; updated_at?: string }
export interface Shipment { id: string; shipment_no: string; shipment_direction: Direction; shipment_type?: string; reference_no?: string; customer_id?: string; supplier_id?: string; customer_name?: string; supplier_name?: string; sales_person?: string; purchase_person?: string; carrier?: string; forwarder?: string; cha?: string; bl_no?: string; booking_no?: string; pol?: string; pod?: string; origin_country?: string; destination_country?: string; incoterms?: string; payment_terms?: string; current_status?: string; current_milestone?: string; eta?: string; previous_eta?: string; etd?: string; vessel?: string; voyage?: string; last_event?: string; last_location?: string; source?: string; confidence?: number; review_status?: string; risk_status?: string; created_by?: string; created_at?: string; updated_at?: string; last_checked_at?: string; closed_at?: string; error?: string }
export interface Container { id: string; shipment_id: string; container_no: string; container_type?: string; seal_no?: string; gross_weight?: number; net_weight?: number; packages?: number; current_status?: string; current_location?: string; eta?: string; last_event?: string; last_checked_at?: string }
export interface ShipmentMilestone { id: string; shipment_id: string; milestone_name: string; milestone_type?: string; planned_date?: string; actual_date?: string; status?: string; delay_days?: number; owner_name?: string; remarks?: string }
export interface DocumentRecord { id: string; shipment_id: string; document_type: string; document_no?: string; document_date?: string; received_date?: string; sent_date?: string; status?: string; file_path?: string; file_url?: string; remarks?: string }
export interface CarrierRule { id: string; carrier: string; active: boolean; tracking_url_pattern: string; number_type?: string; fetch_mode: 'URLFETCH' | 'BROWSER' | 'MANUAL'; input_selector?: string; submit_selector?: string; result_selector?: string; status_regex?: string; eta_regex?: string; etd_regex?: string; vessel_regex?: string; voyage_regex?: string; location_regex?: string; event_regex?: string; captcha_keywords?: string; parser_mode?: string; wait_strategy?: 'TIMEOUT' | 'NETWORK_IDLE' | 'SELECTOR'; wait_seconds?: number; notes?: string }
export interface TrackingJob { id: string; shipment_id: string; carrier: string; tracking_number: string; tracking_number_type?: string; job_status: 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'MANUAL_REVIEW' | 'CANCELLED'; attempts: number; priority?: string; next_run_at?: string; locked_at?: string; locked_by?: string; last_error?: string }
export interface TrackingEvent { id: string; shipment_id: string; container_no?: string; event_date?: string; carrier?: string; tracking_number?: string; status?: string; eta?: string; etd?: string; vessel?: string; voyage?: string; location?: string; raw_event?: string; source?: string; confidence?: number }
export interface ManualReview { id: string; shipment_id: string; tracking_job_id?: string; carrier?: string; tracking_number?: string; reason?: string; carrier_url?: string; manual_text?: string; parsed_json?: unknown; review_status: 'PENDING' | 'APPROVED' | 'REJECTED'; reviewed_by?: string }
export interface Alert { id: string; shipment_id: string; alert_type: string; severity: 'INFO' | 'WARNING' | 'CRITICAL'; message: string; status: 'OPEN' | 'ACKNOWLEDGED' | 'CLOSED'; sent_to?: string }
export interface DashboardSummary { totalActive: number; imports: number; exports: number; delayed: number; arrivingThisWeek: number; manualReviews: number; pendingJobs: number; criticalAlerts: number }
export type WorkerTrackingResult = { success: true; manualReview: false; data: { status?: string; eta?: string; etd?: string; vessel?: string; voyage?: string; location?: string; rawEvent?: string; source?: string; confidence: number } } | { success: false; manualReview: true; reason: string };
